### ISSUE TITLE
Streamline contributor experience / processes 

### ISSUE THREAD

**Issue by tanujkhattar** [iqm-finland/cirq-on-iqm#4]
Cirq has a growing community of contributors and it would be nice if the contributor experience and processes of `cirq-on-iqm` are similar to that of `cirq`. Some concrete suggestions for changes would be
- Have a DEVELOPMENT.md highlighting the contribution process. 
- Run tests/coverage checks on PRs via github actions
- Follow pattern of placing <filename>_test.py files next to <filename>.py

cc @balopat

**Comment by tanujkhattar** [comment]
Also add details about the release process, version naming and decide & document whether we want to make a pre-release version available to users via PyPi or not. Eg: Users can install the latest version of Cirq corresponding to the master branch on github via `pip install --pre Cirq`. Do we want a similar functionality for `cirq-iqm` ?

**Comment by olliahonen** [comment]
In fact coverage has been calculated for a while already. Here's an example of the report under 'Run tests' https://github.com/iqm-finland/cirq-on-iqm/runs/4062982391?check_suite_focus=true
