### ISSUE TITLE
[Feature Request] Early design of user flow for connecting to the IQM Device 

### ISSUE THREAD

**Issue by tanujkhattar** [iqm-finland/cirq-on-iqm#7]
It would be good to start thinking about how the users (for eg: students) would connect to the IQM Device. Ideally, this should also be present in a tutorial notebook.

**Comment by tanujkhattar** [comment]
@smite I think https://github.com/iqm-finland/cirq-on-iqm/commit/dadf2de7bab6e5e38f70f00670e2b9a080eee98e adds the ability of executing circuits on the IQM hardware. I see an `examples/demo_iqm_engine.py` has been added to show the sample usage. Can we also add an authentication notebook tutorial in `docs/`  showing the example usage?

**Comment by olliahonen** [comment]
Currently IQM does not have a public quantum computing service for anyone to sign up at. Those in possession of an IQM quantum computer can, however, connect to that specific system for algorithm execution as [instructed in the user guide](https://iqm-finland.github.io/cirq-on-iqm/user_guide.html#running-on-a-real-quantum-computer) now. The details of the user authentication mechanism will depend on the specific installation, though.

@tanujkhattar would you say that the user flow is now sufficiently outlined in the user guide and the examples?

**Comment by tanujkhattar** [comment]
Looks good for now. Thanks!
